export const CLASSES = {
  dropdown: '^dropdown',
  'dropdown--top': '^dropdown--top',
  'dropdown--top-left': '^dropdown--top-left',
  'dropdown--top-right': '^dropdown--top-right',
  'dropdown--bottom': '^dropdown--bottom',
  'dropdown--bottom-left': '^dropdown--bottom-left',
  'dropdown--bottom-right': '^dropdown--bottom-right',
  dropdown__item: '^dropdown__item',
  'dropdown__item--item': '^dropdown__item--item',
  'dropdown__item--sub': '^dropdown__item--sub',
  'dropdown__item.is-expand': 'is-expand',
  'dropdown__item.is-disabled': 'is-disabled',
  'dropdown__item-icon': '^dropdown__item-icon',
  'dropdown__item-content': '^dropdown__item-content',
  'dropdown__group-list': '^dropdown__group-list',
  'dropdown__group-title': '^dropdown__group-title',
  'dropdown__sub-arrow': '^dropdown__sub-arrow',
  dropdown__list: '^dropdown__list',
  dropdown__empty: '^dropdown__empty',
  dropdown__arrow: '^dropdown__arrow',
  'dropdown-popup': '^dropdown-popup',
};
