export const CLASSES = {
  select: '^select',
  'select.is-expanded': 'is-expanded',
  'select.is-disabled': 'is-disabled',
  'select--small': '^select--small',
  'select--medium': '^select--medium',
  'select--large': '^select--large',
  select__container: '^select__container',
  select__content: '^select__content',
  select__search: '^select__search',
  'select__placeholder-wrapper': '^select__placeholder-wrapper',
  select__placeholder: '^select__placeholder',
  'select__multiple-count': '^select__multiple-count',
  select__close: '^select__close',
  select__clear: '^select__clear',
  select__icon: '^select__icon',
  select__arrow: '^select__arrow',
  'select-popup': '^select-popup',
  'select-popup__content': '^select-popup__content',
  'select-popup__loading': '^select-popup__loading',
  'select-popup__loading--empty': '^select-popup__loading--empty',
  select__list: '^select__list',
  select__option: '^select__option',
  'select__option.is-selected': 'is-selected',
  'select__option.is-disabled': 'is-disabled',
  'select__option-prefix': '^select__option-prefix',
  'select__option-content': '^select__option-content',
  'select__option-group': '^select__option-group',
  'select__option-group-label': '^select__option-group-label',
  select__empty: '^select__empty',
};

export const IS_CREATED = Symbol();
