export const CLASSES = {
  slides: '^slides',
  'slides--vertical': '^slides--vertical',
  'slides--fade': '^slides--fade',
  slides__container: '^slides__container',
  slides__slide: '^slides__slide',
  slides__arrow: '^slides__arrow',
  'slides__arrow.is-hidden': 'is-hidden',
  'slides__arrow--prev': '^slides__arrow--prev',
  'slides__arrow--next': '^slides__arrow--next',
  slides__pagination: '^slides__pagination',
  'slides__pagination.is-hidden': 'is-hidden',
  'slides__pagination--dynamic': '^slides__pagination--dynamic',
  'slides__pagination-radio': '^slides__pagination-radio',
  'slides__pagination-radio.is-checked': 'is-checked',
  'slides__pagination-radio--prev-1': '^slides__pagination-radio--prev-1',
  'slides__pagination-radio--prev-2': '^slides__pagination-radio--prev-2',
  'slides__pagination-radio--next-1': '^slides__pagination-radio--next-1',
  'slides__pagination-radio--next-2': '^slides__pagination-radio--next-2',
};
