export const CLASSES = {
  button: '^button',
  'button.t-primary': 't-primary',
  'button.t-success': 't-success',
  'button.t-warning': 't-warning',
  'button.t-danger': 't-danger',
  'button.is-loading': 'is-loading',
  'button--primary': '^button--primary',
  'button--secondary': '^button--secondary',
  'button--outline': '^button--outline',
  'button--dashed': '^button--dashed',
  'button--text': '^button--text',
  'button--link': '^button--link',
  'button--circle': '^button--circle',
  'button--round': '^button--round',
  'button--block': '^button--block',
  'button--small': '^button--small',
  'button--medium': '^button--medium',
  'button--large': '^button--large',
  'button--icon': '^button--icon',
  'button--icon-right': '^button--icon-right',
  button__icon: '^button__icon',
};
