export const CLASSES = {
  'time-picker': '^time-picker',
  'time-picker.is-disabled': 'is-disabled',
  'time-picker--small': '^time-picker--small',
  'time-picker--medium': '^time-picker--medium',
  'time-picker--large': '^time-picker--large',
  'time-picker__input': '^time-picker__input',
  'time-picker__indicator': '^time-picker__indicator',
  'time-picker__separator': '^time-picker__separator',
  'time-picker__clear': '^time-picker__clear',
  'time-picker__icon': '^time-picker__icon',
  'time-picker-popup': '^time-picker-popup',
  'time-picker__panel': '^time-picker__panel',
  'time-picker__header': '^time-picker__header',
  'time-picker__column': '^time-picker__column',
  'time-picker__cell': '^time-picker__cell',
  'time-picker__cell.is-active': 'is-active',
  'time-picker__cell.is-disabled': 'is-disabled',
  'time-picker__footer': '^time-picker__footer',
};
