export const CLASSES = {
  stepper: '^stepper',
  'stepper--button': '^stepper--button',
  'stepper--label-bottom': '^stepper--label-bottom',
  'stepper--vertical': '^stepper--vertical',
  stepper__step: '^stepper__step',
  'stepper__step.is-wait': 'is-wait',
  'stepper__step.is-active': 'is-active',
  'stepper__step.is-completed': 'is-completed',
  'stepper__step.is-warning': 'is-warning',
  'stepper__step.is-error': 'is-error',
  'stepper__step-header': '^stepper__step-header',
  'stepper__step-title': '^stepper__step-title',
  'stepper__step-description': '^stepper__step-description',
  'stepper__step-dot': '^stepper__step-dot',
  'stepper__step-dot--progress': '^stepper__step-dot--progress',
  'stepper__step-separator': '^stepper__step-separator',
  'stepper__step-progress': '^stepper__step-progress',
};
