export const CLASSES = {
  menu: '^menu',
  'menu--horizontal': '^menu--horizontal',
  menu__item: '^menu__item',
  'menu__item--item': '^menu__item--item',
  'menu__item--sub': '^menu__item--sub',
  'menu__item--horizontal': '^menu__item--horizontal',
  'menu__item--icon': '^menu__item--icon',
  'menu__item.is-active': 'is-active',
  'menu__item.is-expand': 'is-expand',
  'menu__item.is-disabled': 'is-disabled',
  'menu__item-icon': '^menu__item-icon',
  'menu__item-content': '^menu__item-content',
  'menu__group-list': '^menu__group-list',
  'menu__group-title': '^menu__group-title',
  'menu__sub-list': '^menu__sub-list',
  'menu__sub-arrow': '^menu__sub-arrow',
  'menu__sub-arrow--horizontal': '^menu__sub-arrow--horizontal',
  'menu__sub-arrow.is-expand': 'is-expand',
  menu__indicator: '^menu__indicator',
  'menu__indicator--first': '^menu__indicator--first',
  'menu__indicator--last': '^menu__indicator--last',
  'menu__indicator-track': '^menu__indicator-track',
  'menu__indicator-track--hidden': '^menu__indicator-track--hidden',
  'menu__indicator-thumb': '^menu__indicator-thumb',
  menu__empty: '^menu__empty',
  'menu-popup': '^menu-popup',
};
