export const CLASSES = {
  timeline: '^timeline',
  'timeline--vertical': '^timeline--vertical',
  timeline__content: '^timeline__content',
  'timeline__content--gap': '^timeline__content--gap',
  'timeline__text-container': '^timeline__text-container',
  timeline__text: '^timeline__text',
  'timeline__text--left': '^timeline__text--left',
  'timeline__track-container': '^timeline__track-container',
  timeline__track: '^timeline__track',
  'timeline__track.is-wait': 'is-wait',
  'timeline__track.is-active': 'is-active',
  'timeline__track.is-completed': 'is-completed',
  'timeline__track.is-warning': 'is-warning',
  'timeline__track.is-error': 'is-error',
  timeline__dot: '^timeline__dot',
  timeline__separator: '^timeline__separator',
  'timeline__separator--hidden': '^timeline__separator--hidden',
};
